[build]
  command = "npm install"
  functions = "functions"

[[redirects]]
  from = "/api/threads/*"
  to = "/.netlify/functions/threads/:splat"
  method = "GET"

[[headers]]
  for = "/api/threads/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = []
